days_to_schedule:
  62
  
skip_weekends:
  false
  
skip_holidays:
  false

predefined_shift_order:
- Sherry
- Boris
- Vicente
- Matte
- Jack
- Sherry
- Matte
- Kevin
- Kevin
- Vicente
- Zoe
- Kevin
- Matte
- Zoe
- Jay
- Boris
- Eadon
- Sherry
- Franky
- Sherry
- Matte
- Franky
- Franky
- Kevin
- Boris
- Franky
- Vicente
- Luis
- Eadon
- Boris
- Kevin
- Matte
- Jay
- James
- Kevin
- Sherry
- Sherry
- Jack
- Sherry
- Jack